const translations = {
  fr: {
    about_title: "À propos de nous",
    formations_title: "Nos Formations",
    brochure: "📄 Brochure",
    signup: "S'inscrire maintenant",
    vision_title: "Notre Vision & Mission",
    vision: "Vision",
    vision_text: "Contribuer à l'avenir du Burkina Faso grâce à une formation informatique de pointe centrée sur l’IA et l’innovation numérique.",
    mission: "Mission",
    mission_text: "Créer un vivier de talents technologiques via des formations abordables, pratiques, et connectées aux besoins du marché.",
    pourquoi: "Pourquoi le Burkina Faso ?",
    pourquoi_text: "Une jeunesse dynamique avec un fort potentiel numérique. Le pays est un pôle francophone stratégique en Afrique de l’Ouest.",
    valeurs_title: "Nos Valeurs",
    excellence: "Excellence",
    excellence_text: "Former une élite technologique compétente et innovante.",
    accessibilite: "Accessibilité",
    accessibilite_text: "Rendre l'éducation numérique accessible à la jeunesse africaine.",
    innovation: "Innovation",
    innovation_text: "Promouvoir les technologies de pointe (IA, Cloud, Sécurité, Data).",
    ethique: "Éthique",
    ethique_text: "Développer des talents responsables, citoyens du numérique.",
    impact: "Impact Social",
    impact_text: "Stimuler l’employabilité et l’entrepreneuriat digital.",
    partenaires_title: "Nos partenaires",
    expansion_title: "Déploiement & Expansion",
    phase1: "Phase 1 : Déploiement du premier centre à Bobo-Dioulasso",
    phase2: "Phase 2 : Expansion vers le Mali, Niger, Côte d’Ivoire via franchises"
  },
  en: {
    about_title: "About Us",
    formations_title: "Our Trainings",
    brochure: "📄 Brochure",
    signup: "Register now",
    vision_title: "Our Vision & Mission",
    vision: "Vision",
    vision_text: "Contribute to Burkina Faso's future with cutting-edge IT training focused on AI and digital innovation.",
    mission: "Mission",
    mission_text: "Create a pool of tech talent through affordable, hands-on training aligned with market needs.",
    pourquoi: "Why Burkina Faso?",
    pourquoi_text: "A dynamic youth with strong digital potential. The country is a strategic Francophone hub in West Africa.",
    valeurs_title: "Our Values",
    excellence: "Excellence",
    excellence_text: "Train competent and innovative tech leaders.",
    accessibilite: "Accessibility",
    accessibilite_text: "Make digital education accessible to African youth.",
    innovation: "Innovation",
    innovation_text: "Promote cutting-edge technologies (AI, Cloud, Security, Data).",
    ethique: "Ethics",
    ethique_text: "Develop responsible digital citizens.",
    impact: "Social Impact",
    impact_text: "Boost employability and digital entrepreneurship.",
    partenaires_title: "Our Partners",
    expansion_title: "Deployment & Expansion",
    phase1: "Phase 1: Launch of the first center in Bobo-Dioulasso",
    phase2: "Phase 2: Expansion to Mali, Niger, and Côte d’Ivoire via franchises"
  }
};
